export const platforms = [
  {
    id: 'binance',
    name: 'BINANCE',
    descriptor: 'FUTURES',
    className: 'theme-binance',
    mode: 'futures',
  },
  {
    id: 'okx',
    name: 'OKX',
    descriptor: 'PERPETUAL',
    className: 'theme-okx',
    mode: 'futures',
  },
  {
    id: 'hyperliquid',
    name: 'HYPERLIQUID',
    descriptor: 'PERPS',
    className: 'theme-hyperliquid',
    mode: 'futures',
  },
  {
    id: 'bybit',
    name: 'BYBIT',
    descriptor: 'PERPETUAL',
    className: 'theme-bybit',
    mode: 'futures',
    defaults: {
      pair: 'ETH/USDT', side: 'LONG', leverage: '10', pnl: '6.29', profit: '7.09',
      entry: '2,207.23', exit: '2,221.28', invested: '1.12', handle: 'larpitalist',
    },
  },
  {
    id: 'mexc',
    name: 'MEXC',
    descriptor: 'FUTURES',
    className: 'theme-mexc',
    mode: 'futures',
    defaults: {
      pair: 'OIL/USDT', side: 'SHORT', leverage: '20', pnl: '32.35', profit: '54.80',
      entry: '89.81', exit: '89.814', invested: '0.0548', handle: 'larpitalist',
    },
  },
  {
    id: 'axiom',
    name: 'AXIOM',
    descriptor: 'MEMECOINS',
    className: 'theme-axiom',
    mode: 'memecoin',
    backgrounds: [
      { label: 'Axiom Pro', src: '/axiom-gallery-1.jpg' },
      { label: 'Axiom shards', src: '/axiom-gallery-2.jpg' },
      { label: 'Axiom cyan', src: '/axiom-gallery-3.png' },
    ],
    defaults: {
      pair: 'LARP',
      pnl: '214.75',
      profit: '2.74K',
      invested: '1.28K',
      position: '4.02K',
      handle: 'larpitalist',
    },
  },
  {
    id: 'gmgn',
    name: 'GMGN',
    descriptor: 'MEMECOINS',
    className: 'theme-gmgn',
    mode: 'memecoin',
    defaults: {
      pair: 'LARP',
      pnl: '643.03',
      profit: '300.94',
      invested: '43.3',
      hold: '96.9',
      sold: '302.24',
      multiplier: '13.13K',
      inviteCode: 'larp',
      displayName: 'Sheep',
      handle: 'larpitalist',
    },
  },
  {
    id: 'padre',
    name: 'TERMINAL',
    descriptor: 'PADRE',
    className: 'theme-padre',
    mode: 'memecoin',
    backgrounds: [
      { label: 'Terminal silver', src: '/terminal-gallery-1.png' },
      { label: 'Terminal void', src: '/terminal-gallery-2.png' },
    ],
    defaults: {
      pair: 'LARP',
      pnl: '-7.13',
      profit: '-34.60',
      invested: '484.89',
      sold: '450.29',
      date: '3 Aug 2026',
      handle: 'larpitalist',
    },
  },
  {
    id: 'bullx',
    name: 'BULLX',
    descriptor: 'MEMECOINS',
    className: 'theme-bullx',
    mode: 'memecoin',
    defaults: {
      pair: 'LARP',
      pnl: '214.75',
      profit: '2.83',
      invested: '524.31',
      sold: '971.74',
      position: '447.43',
      handle: 'larpitalist',
    },
  },
  {
    id: 'photon',
    name: 'PHOTON',
    descriptor: 'SOL',
    className: 'theme-photon',
    mode: 'memecoin',
    defaults: {
      pair: 'LARP',
      pnl: '242.53',
      profit: '7.2758',
      invested: '3.0',
      position: '1349.5058',
      sold: '556.4336',
    },
  },
  {
    id: 'jupiter',
    name: 'JUPITER',
    descriptor: 'MOBILE',
    className: 'theme-jupiter',
    mode: 'memecoin',
    defaults: {
      pair: 'LARP',
      pnl: '6407',
      profit: '33.41K',
      invested: '521.50',
      entry: '36.11K',
      position: '2.89M',
      displayName: 'larpitalist',
      date: '06 Aug 26',
    },
  },
  {
    id: 'fomo',
    name: 'FOMO',
    descriptor: 'MEMECOINS',
    className: 'theme-fomo',
    mode: 'memecoin',
    defaults: {
      pair: 'LARP', displayName: 'LARP', profit: '20,213.54', pnl: '451.22',
      invested: '4.4K', entry: '256.2K', exit: '1.4M', date: 'Jul 26, 2026',
      handle: 'larpitalist', inviteCode: 'larpitalism',
    },
  },
  {
    id: 'pumpfun',
    name: 'PUMP.FUN',
    descriptor: 'APP',
    className: 'theme-pumpfun',
    mode: 'memecoin',
    defaults: {
      pair: 'LARP', displayName: 'Larp Coin', profit: '265.99', pnl: '72.34',
      entry: '74.28K', position: '116.83K', handle: 'larpitalist',
    },
  },
  {
    id: 'moonshot',
    name: 'MOONSHOT',
    descriptor: 'MEMECOINS',
    className: 'theme-moonshot',
    mode: 'memecoin',
    defaults: {
      pair: 'LARP', displayName: 'LARP', profit: '4,218.37', pnl: '684.21',
      invested: '616.52', entry: '82.4K', position: '4.83K',
      handle: 'larpitalist', date: 'Aug 10, 2026',
    },
  },
  {
    id: 'trojan',
    name: 'TROJAN',
    descriptor: 'SOLANA BOT',
    className: 'theme-trojan',
    mode: 'memecoin',
    defaults: {
      pair: 'LARP', profit: '42.69', pnl: '1337.42', invested: '3.19',
      sold: '45.88', entry: '74.2K', position: '1.07M', handle: 'larpitalist',
    },
  },
  {
    id: 'phantom',
    name: 'PHANTOM',
    descriptor: 'WALLET',
    className: 'theme-phantom',
    mode: 'wallet',
    defaults: {
      handle: 'larpitalist',
      walletName: 'Larpitalism Wallet',
      walletBalance: '1,153.48',
      profit: '-22.76',
      pnl: '-1.94',
      pair: 'LARP',
      tokenSymbol: 'LARP',
      tokenAmount: '8,994,980',
      tokenValue: '1,153.48',
      tokenPnl: '-22.76',
    },
  },
]

export const futuresPresets = [
  { pair: 'LARP/USDT', side: 'LONG', leverage: '100', pnl: '42069.69', profit: '84,139.38', entry: '0.000042', exit: '0.017681', invested: '2.00' },
  { pair: 'COPE/SOL', side: 'LONG', leverage: '50', pnl: '1337.42', profit: '6,954.58', entry: '0.00031', exit: '0.00446', invested: '520.00' },
  { pair: 'BTC/USDT', side: 'SHORT', leverage: '125', pnl: '911.08', profit: '41,001.17', entry: '118,420.50', exit: '109,783.22', invested: '4,500.00' },
  { pair: 'ETH/USDT', side: 'LONG', leverage: '75', pnl: '808.15', profit: '12,972.44', entry: '3,488.40', exit: '3,864.22', invested: '1,604.99' },
]

export const memecoinPresets = [
  { pair: 'LARP', displayName: 'Sheep', pnl: '643.03', profit: '300.94', invested: '43.3', position: '344.24', hold: '96.9', sold: '302.24', multiplier: '13.13K' },
  { pair: 'COPE', displayName: 'Paperhands', pnl: '214.75', profit: '2.74K', invested: '1.28K', position: '4.02K', hold: '1.19K', sold: '2.83K', multiplier: '7.42K' },
  { pair: 'BAGS', displayName: 'Roundtripper', pnl: '-7.13', profit: '-34.60', invested: '484.89', position: '450.29', hold: '0', sold: '450.29', multiplier: '0.93X' },
  { pair: 'TRENCH', displayName: 'Trenchlord', pnl: '8008.15', profit: '12.97K', invested: '162.00', position: '13.13K', hold: '4.18K', sold: '8.95K', multiplier: '81.04K' },
]
